package com.faridrama123.app.utils

import com.faridrama123.app.data.source.local.entity.MovieEntity
import com.faridrama123.app.data.source.local.entity.TVShowEntity
import com.faridrama123.app.data.source.remote.response.ResultsMovieResponse
import com.faridrama123.app.data.source.remote.response.ResultsTVShowResponse
import java.util.ArrayList

object DataDummy {

    fun generateDummyMovie(): ArrayList<MovieEntity> {

        val movie = ArrayList<MovieEntity>()

        movie.add(MovieEntity("Freddy Lupin, heir to a proud family line of werewolves, is in for a shock when on his 14th birthday his first 'warfing' goes awry, turning him into a ferocious poodle. The pack elders give Freddy until the next moonrise to prove he has the heart of a wolf, or risk being cast out forever. With the help of an unlikely ally in a streetwise stray named Batty, Freddy must prove he's 100% Wolf.","en","100% Wolf",false,"100% Wolf",listOf(10751, 16, 14),"/2VrvxK4yxNCU6KVgo5TADJeBEQu.jpg","/7TxeZVg2evMG42p0uSbMJpWNQ8A.jpg","2020-06-26",687.431,6.0,520946,false,73,false))
        movie.add(MovieEntity("Stagnant since 1903, at an elevation of 9000', a volcano erupts on the mythical and majestic Baekdu Mountain.","ko","백두산",false,"Ashfall",listOf(28, 12, 53),"/zoeKREZ2IdAUnXISYCS0E6H5BVh.jpg","/h9DIlghaiTxbQbt1FIwKNbQvEL.jpg","2019-12-19",763.976,6.7,581387,false,183,false))
        movie.add(MovieEntity("A black ops assassin is forced to fight for her own survival after a job goes dangerously wrong.","en","Ava",false,"Ava",listOf(28, 80, 18, 53),"/qzA87Wf4jo1h8JMk9GilyIYvwsA.jpg","/54yOImQgj8i85u9hxxnaIQBRUuo.jpg","2020-07-02",788.909,5.6,539885,false,1239,false))
        movie.add(MovieEntity("When a prisoner transfer van is attacked, the cop in charge must fight those inside and outside while dealing with a silent foe: the icy temperatures.","es","Bajocero",false,"Below Zero",listOf(28, 80, 53),"/dWSnsAGTfc8U27bWsy2RfwZs0Bs.jpg","/6TPZSJ06OEXeelx1U1VIAt0j9Ry.jpg","2021-01-29",2031.873,6.4,587996,false,258,false))
        movie.add(MovieEntity("Harley Quinn joins forces with a singer, an assassin and a police detective to help a young girl who had a hit placed on her after she stole a rare diamond from a crime lord.","en","Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)",false,"Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)",listOf(28, 80),"/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg","/9xNOiv6DZZjH7ABoUUDP0ZynouU.jpg","2020-02-05",645.079,7.1,495764,false,6878,false))




        movie.add(MovieEntity("Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s and finds a formidable foe by the name of the Cheetah.","en","Wonder Woman 1984",false,"Wonder Woman 1984",listOf(14, 28, 12),"/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg","/srYya1ZlI97Au4jUYAktDe3avyA.jpg","2020-12-16",2198.624,7.0,464052,false,3512,false))
        movie.add(MovieEntity("Deputy Sheriff Joe Deke Deacon joins forces with Sgt. Jim Baxter to search for a serial killer who's terrorizing Los Angeles. As they track the culprit, Baxter is unaware that the investigation is dredging up echoes of Deke's past, uncovering disturbing secrets that could threaten more than his case.","en","The Little Things",false,"The Little Things",listOf(53, 80),"/c7VlGCCgM9GZivKSzBgzuOVxQn7.jpg","/vfuzELmhBjBTswXj2Vqxnu5ge4g.jpg","2021-01-27",1700.385,6.4,602269,false,269,false))
        movie.add(MovieEntity("In the near future, a drone pilot is sent into a deadly militarized zone and must work with an android officer to locate a doomsday device.","en","Outside the Wire",false,"Outside the Wire",listOf(53, 28, 878),"/6XYLiMxHAaCsoyrVo38LBWMw2p8.jpg","/lOSdUkGQmbAl5JQ3QoHqBZUbZhC.jpg","2021-01-15",1388.513,6.5,775996,false,654,false))
        movie.add(MovieEntity("An adventure-loving couple convince their friends to explore a remote, uncharted cave system in the forests of Northern Australia. With a tropical storm approaching, they abseil into the mouth of the cave, but when the caves start to flood, tensions rise as oxygen levels fall and the friends find themselves trapped. Unknown to them, the storm has also brought in a pack of dangerous and hungry crocodiles.","en","Black Water: Abyss",false,"Black Water: Abyss",listOf(27, 53, 12),"/95S6PinQIvVe4uJAd82a2iGZ0rA.jpg","/fRrpOILyXuWaWLmqF7kXeMVwITQ.jpg","2020-07-09",1343.587,5.1,522444,false,119,false))
        movie.add(MovieEntity("Covert security company Vanguard is the last hope of survival for an accountant after he is targeted by the world's deadliest mercenary organization.","zh","急先锋",false,"Vanguard",listOf(28, 12, 80),"/vYvppZMvXYheYTWVd8Rnn9nsmNp.jpg","/fX8e94MEWSuTJExndVYxKsmA4Hw.jpg","2020-09-30",1180.424,6.6,604822,false,185,false))
        movie.add(MovieEntity("A hardened mechanic must stay awake and maintain an interstellar ark fleeing the dying planet Earth with a few thousand lucky souls on board... the last of humanity. Unfortunately, humans are not the only passengers. A shapeshifting alien creature has taken residence, its only goal is to kill as many people as possible. The crew must think quickly to stop this menace before it destroys mankind.","en","Breach",false,"Breach",listOf(878, 28),"/13B6onhL6FzSN2KaNeQeMML05pS.jpg","/nz8xWrTKZzA5A7FgxaM4kfAoO1W.jpg","2020-12-17",1145.204,4.7,651571,false,229,false))
        movie.add(MovieEntity("Joe Gardner is a middle school teacher with a love for jazz music. After a successful gig at the Half Note Club, he suddenly gets into an accident that separates his soul from his body and is transported to the You Seminar, a center in which souls develop and gain passions before being transported to a newborn child. Joe must enlist help from the other souls-in-training, like 22, a soul who has spent eons in the You Seminar, in order to get back to Earth.","en","Soul",false,"Soul",listOf(10751, 16, 35, 18, 10402, 14),"/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg","/kf456ZqeC45XTvo6W9pW5clYKfQ.jpg","2020-12-25",1024.47,8.3,508442,false,4686,false))
        movie.add(MovieEntity("When a virus threatens to turn the now earth-dwelling friendly alien hybrids against humans, Captain Rose Corley must lead a team of elite mercenaries on a mission to the alien world in order to save what's left of humanity.","en","Skylines",false,"Skylines",listOf(878, 28),"/2W4ZvACURDyhiNnSIaFPHfNbny3.jpg","/3ombg55JQiIpoPnXYb2oYdr6DtP.jpg","2020-10-25",1015.978,5.7,560144,false,162,false))
        movie.add(MovieEntity("Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.","en","Tenet",false,"Tenet",listOf(28, 53, 878),"/k68nPLbIST6NP96JmTxmZijEvCA.jpg","/wzJRB4MKi3yK138bJyuL9nx47y6.jpg","2020-08-22",915.538,7.3,577922,false,4329,false))
        movie.add(MovieEntity("Two Brooklyn siblings' summer in a rural Oahu town takes an exciting turn when a journal pointing to long-lost treasure sets them on an adventure, leading them to reconnect with their Hawaiian heritage.","en","Finding 'Ohana",false,"Finding 'Ohana",listOf(28, 12, 35, 10751),"/tTWl37oAYRXS3D5mEHmjveXXyrN.jpg","/yImmxRokQ48PD49ughXdpKTAsAU.jpg","2021-01-29",951.554,6.9,644092,false,102,false))
        movie.add(MovieEntity("A former Marine turned doorman at a luxury New York City high-rise must outsmart and battle a group of art thieves and their ruthless leader — while struggling to protect her sister's family. As the thieves become increasingly desperate and violent, the doorman calls upon her deadly fighting skills to end the showdown.","en","The Doorman",false,"The Doorman",listOf(28, 53),"/pklyUbh4k1DbHdnsOMASyw7C6NH.jpg","/9pHxv7TX0jOKNgnGMDP6RJ2m1GL.jpg","2020-10-01",696.255,5.8,737568,false,153,false))
        movie.add(MovieEntity("A bank robber tries to turn himself in because he's falling in love and wants to live an honest life...but when he realizes the Feds are more corrupt than him, he must fight back to clear his name.","en","Honest Thief",false,"Honest Thief",listOf(53, 28, 80, 18),"/zeD4PabP6099gpE0STWJrJrCBCs.jpg","/2M2JxEv3HSpjnZWjY9NOdGgfUd.jpg","2020-09-03",672.937,6.6,553604,false,582,false))
        movie.add(MovieEntity("Searching for a safer habitat, the prehistoric Crood family discovers an idyllic, walled-in paradise that meets all of its needs. Unfortunately, they must also learn to live with the Bettermans -- a family that's a couple of steps above the Croods on the evolutionary ladder. As tensions between the new neighbors start to rise, a new threat soon propels both clans on an epic adventure that forces them to embrace their differences, draw strength from one another, and survive together.","en","The Croods: A New Age",false,"The Croods: A New Age",listOf(10751, 12, 14, 16),"/tK1zy5BsCt1J4OzoDicXmr0UTFH.jpg","/cjaOSjsjV6cl3uXdJqimktT880L.jpg","2020-11-25",629.468,7.6,529203,false,1451,false))
        movie.add(MovieEntity("David Cuevas is a family man who works as a gangland tax collector for high ranking Los Angeles gang members. He makes collections across the city with his partner Creeper making sure people pay up or will see retaliation. An old threat returns to Los Angeles that puts everything David loves in harm’s way.","en","The Tax Collector",false,"The Tax Collector",listOf(28, 80, 18),"/3eg0kGC2Xh0vhydJHO37Sp4cmMt.jpg","/zogWnCSztU8xvabaepQnAwsOtOt.jpg","2020-08-07",583.617,5.8,531499,false,249,false))
        movie.add(MovieEntity("During a school field trip, Ladybug and Cat Noir meet the American superheroes, whom they have to save from an akumatised super-villain. They discover that Miraculous exist in the United States too.","fr","Miraculous World: New York, United HeroeZ",false,"Miraculous World: New York, United HeroeZ",listOf(16, 10751),"/kIHgjAkuzvKBnmdstpBOo4AfZah.jpg","/yR27bZPIkNhpGEIP3jKV2EifTgo.jpg","2020-09-26",622.069,8.5,755812,false,376,false))

        return movie
    }
    fun generateRemoteDummyMovie(): ArrayList<ResultsMovieResponse> {

        val movie = ArrayList<ResultsMovieResponse>()
        movie.add(ResultsMovieResponse("Freddy Lupin, heir to a proud family line of werewolves, is in for a shock when on his 14th birthday his first 'warfing' goes awry, turning him into a ferocious poodle. The pack elders give Freddy until the next moonrise to prove he has the heart of a wolf, or risk being cast out forever. With the help of an unlikely ally in a streetwise stray named Batty, Freddy must prove he's 100% Wolf.","en","100% Wolf",false,"100% Wolf",listOf(10751, 16, 14),"/2VrvxK4yxNCU6KVgo5TADJeBEQu.jpg","/7TxeZVg2evMG42p0uSbMJpWNQ8A.jpg","2020-06-26",687.431,6.0,520946,false,73))
        movie.add(ResultsMovieResponse("Stagnant since 1903, at an elevation of 9000', a volcano erupts on the mythical and majestic Baekdu Mountain.","ko","백두산",false,"Ashfall",listOf(28, 12, 53),"/zoeKREZ2IdAUnXISYCS0E6H5BVh.jpg","/h9DIlghaiTxbQbt1FIwKNbQvEL.jpg","2019-12-19",763.976,6.7,581387,false,183))
        movie.add(ResultsMovieResponse("A black ops assassin is forced to fight for her own survival after a job goes dangerously wrong.","en","Ava",false,"Ava",listOf(28, 80, 18, 53),"/qzA87Wf4jo1h8JMk9GilyIYvwsA.jpg","/54yOImQgj8i85u9hxxnaIQBRUuo.jpg","2020-07-02",788.909,5.6,539885,false,1239))
        movie.add(ResultsMovieResponse("When a prisoner transfer van is attacked, the cop in charge must fight those inside and outside while dealing with a silent foe: the icy temperatures.","es","Bajocero",false,"Below Zero",listOf(28, 80, 53),"/dWSnsAGTfc8U27bWsy2RfwZs0Bs.jpg","/6TPZSJ06OEXeelx1U1VIAt0j9Ry.jpg","2021-01-29",2031.873,6.4,587996,false,258))
        movie.add(ResultsMovieResponse("Harley Quinn joins forces with a singer, an assassin and a police detective to help a young girl who had a hit placed on her after she stole a rare diamond from a crime lord.","en","Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)",false,"Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)",listOf(28, 80),"/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg","/9xNOiv6DZZjH7ABoUUDP0ZynouU.jpg","2020-02-05",645.079,7.1,495764,false,6878))




        movie.add(ResultsMovieResponse("Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s and finds a formidable foe by the name of the Cheetah.","en","Wonder Woman 1984",false,"Wonder Woman 1984",listOf(14, 28, 12),"/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg","/srYya1ZlI97Au4jUYAktDe3avyA.jpg","2020-12-16",2198.624,7.0,464052,false,3512))
        movie.add(ResultsMovieResponse("Deputy Sheriff Joe Deke Deacon joins forces with Sgt. Jim Baxter to search for a serial killer who's terrorizing Los Angeles. As they track the culprit, Baxter is unaware that the investigation is dredging up echoes of Deke's past, uncovering disturbing secrets that could threaten more than his case.","en","The Little Things",false,"The Little Things",listOf(53, 80),"/c7VlGCCgM9GZivKSzBgzuOVxQn7.jpg","/vfuzELmhBjBTswXj2Vqxnu5ge4g.jpg","2021-01-27",1700.385,6.4,602269,false,269))
        movie.add(ResultsMovieResponse("In the near future, a drone pilot is sent into a deadly militarized zone and must work with an android officer to locate a doomsday device.","en","Outside the Wire",false,"Outside the Wire",listOf(53, 28, 878),"/6XYLiMxHAaCsoyrVo38LBWMw2p8.jpg","/lOSdUkGQmbAl5JQ3QoHqBZUbZhC.jpg","2021-01-15",1388.513,6.5,775996,false,654))
        movie.add(ResultsMovieResponse("An adventure-loving couple convince their friends to explore a remote, uncharted cave system in the forests of Northern Australia. With a tropical storm approaching, they abseil into the mouth of the cave, but when the caves start to flood, tensions rise as oxygen levels fall and the friends find themselves trapped. Unknown to them, the storm has also brought in a pack of dangerous and hungry crocodiles.","en","Black Water: Abyss",false,"Black Water: Abyss",listOf(27, 53, 12),"/95S6PinQIvVe4uJAd82a2iGZ0rA.jpg","/fRrpOILyXuWaWLmqF7kXeMVwITQ.jpg","2020-07-09",1343.587,5.1,522444,false,119))
        movie.add(ResultsMovieResponse("Covert security company Vanguard is the last hope of survival for an accountant after he is targeted by the world's deadliest mercenary organization.","zh","急先锋",false,"Vanguard",listOf(28, 12, 80),"/vYvppZMvXYheYTWVd8Rnn9nsmNp.jpg","/fX8e94MEWSuTJExndVYxKsmA4Hw.jpg","2020-09-30",1180.424,6.6,604822,false,185))
        movie.add(ResultsMovieResponse("A hardened mechanic must stay awake and maintain an interstellar ark fleeing the dying planet Earth with a few thousand lucky souls on board... the last of humanity. Unfortunately, humans are not the only passengers. A shapeshifting alien creature has taken residence, its only goal is to kill as many people as possible. The crew must think quickly to stop this menace before it destroys mankind.","en","Breach",false,"Breach",listOf(878, 28),"/13B6onhL6FzSN2KaNeQeMML05pS.jpg","/nz8xWrTKZzA5A7FgxaM4kfAoO1W.jpg","2020-12-17",1145.204,4.7,651571,false,229))
        movie.add(ResultsMovieResponse("Joe Gardner is a middle school teacher with a love for jazz music. After a successful gig at the Half Note Club, he suddenly gets into an accident that separates his soul from his body and is transported to the You Seminar, a center in which souls develop and gain passions before being transported to a newborn child. Joe must enlist help from the other souls-in-training, like 22, a soul who has spent eons in the You Seminar, in order to get back to Earth.","en","Soul",false,"Soul",listOf(10751, 16, 35, 18, 10402, 14),"/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg","/kf456ZqeC45XTvo6W9pW5clYKfQ.jpg","2020-12-25",1024.47,8.3,508442,false,4686))
        movie.add(ResultsMovieResponse("When a virus threatens to turn the now earth-dwelling friendly alien hybrids against humans, Captain Rose Corley must lead a team of elite mercenaries on a mission to the alien world in order to save what's left of humanity.","en","Skylines",false,"Skylines",listOf(878, 28),"/2W4ZvACURDyhiNnSIaFPHfNbny3.jpg","/3ombg55JQiIpoPnXYb2oYdr6DtP.jpg","2020-10-25",1015.978,5.7,560144,false,162))
        movie.add(ResultsMovieResponse("Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.","en","Tenet",false,"Tenet",listOf(28, 53, 878),"/k68nPLbIST6NP96JmTxmZijEvCA.jpg","/wzJRB4MKi3yK138bJyuL9nx47y6.jpg","2020-08-22",915.538,7.3,577922,false,4329))
        movie.add(ResultsMovieResponse("Two Brooklyn siblings' summer in a rural Oahu town takes an exciting turn when a journal pointing to long-lost treasure sets them on an adventure, leading them to reconnect with their Hawaiian heritage.","en","Finding 'Ohana",false,"Finding 'Ohana",listOf(28, 12, 35, 10751),"/tTWl37oAYRXS3D5mEHmjveXXyrN.jpg","/yImmxRokQ48PD49ughXdpKTAsAU.jpg","2021-01-29",951.554,6.9,644092,false,102))
        movie.add(ResultsMovieResponse("A former Marine turned doorman at a luxury New York City high-rise must outsmart and battle a group of art thieves and their ruthless leader — while struggling to protect her sister's family. As the thieves become increasingly desperate and violent, the doorman calls upon her deadly fighting skills to end the showdown.","en","The Doorman",false,"The Doorman",listOf(28, 53),"/pklyUbh4k1DbHdnsOMASyw7C6NH.jpg","/9pHxv7TX0jOKNgnGMDP6RJ2m1GL.jpg","2020-10-01",696.255,5.8,737568,false,153))
        movie.add(ResultsMovieResponse("A bank robber tries to turn himself in because he's falling in love and wants to live an honest life...but when he realizes the Feds are more corrupt than him, he must fight back to clear his name.","en","Honest Thief",false,"Honest Thief",listOf(53, 28, 80, 18),"/zeD4PabP6099gpE0STWJrJrCBCs.jpg","/2M2JxEv3HSpjnZWjY9NOdGgfUd.jpg","2020-09-03",672.937,6.6,553604,false,582))
        movie.add(ResultsMovieResponse("Searching for a safer habitat, the prehistoric Crood family discovers an idyllic, walled-in paradise that meets all of its needs. Unfortunately, they must also learn to live with the Bettermans -- a family that's a couple of steps above the Croods on the evolutionary ladder. As tensions between the new neighbors start to rise, a new threat soon propels both clans on an epic adventure that forces them to embrace their differences, draw strength from one another, and survive together.","en","The Croods: A New Age",false,"The Croods: A New Age",listOf(10751, 12, 14, 16),"/tK1zy5BsCt1J4OzoDicXmr0UTFH.jpg","/cjaOSjsjV6cl3uXdJqimktT880L.jpg","2020-11-25",629.468,7.6,529203,false,1451))
        movie.add(ResultsMovieResponse("David Cuevas is a family man who works as a gangland tax collector for high ranking Los Angeles gang members. He makes collections across the city with his partner Creeper making sure people pay up or will see retaliation. An old threat returns to Los Angeles that puts everything David loves in harm’s way.","en","The Tax Collector",false,"The Tax Collector",listOf(28, 80, 18),"/3eg0kGC2Xh0vhydJHO37Sp4cmMt.jpg","/zogWnCSztU8xvabaepQnAwsOtOt.jpg","2020-08-07",583.617,5.8,531499,false,249))
        movie.add(ResultsMovieResponse("During a school field trip, Ladybug and Cat Noir meet the American superheroes, whom they have to save from an akumatised super-villain. They discover that Miraculous exist in the United States too.","fr","Miraculous World: New York, United HeroeZ",false,"Miraculous World: New York, United HeroeZ",listOf(16, 10751),"/kIHgjAkuzvKBnmdstpBOo4AfZah.jpg","/yR27bZPIkNhpGEIP3jKV2EifTgo.jpg","2020-09-26",622.069,8.5,755812,false,376))

        return movie
    }


    fun generateDummyTVShow ()  : ArrayList<TVShowEntity> {
        val tvshow = ArrayList <TVShowEntity>()

            tvshow.add(TVShowEntity("2017-04-30","An ex-con becomes the traveling partner of a conman who turns out to be one of the older gods trying to recruit troops to battle the upstart deities. Based on Neil Gaiman's fantasy novel.","en", listOf(18, 9648, 10765),"/3KCAZaKHmoMIN9dHutqaMtubQqD.jpg",listOf("US"),"/7dnjFPoa22Yl3RKctp8kgUxiUg9.jpg","American Gods",344.643,7.1,"American Gods",46639,925,false))
            tvshow.add(TVShowEntity("2018-05-02","This Karate Kid sequel series picks up 30 years after the events of the 1984 All Valley Karate Tournament and finds Johnny Lawrence on the hunt for redemption by reopening the infamous Cobra Kai karate dojo. This reignites his old rivalry with the successful Daniel LaRusso, who has been working to maintain the balance in his life without mentor Mr. Miyagi.","en", listOf(10759, 18),"/obLBdhLxheKg8Li1qO11r2SwmYO.jpg",listOf("US"),"/gL8myjGc2qrmqVosyGm5CWTir9A.jpg","Cobra Kai",636.126,8.1,"Cobra Kai",77169,2481,false))
            tvshow.add(TVShowEntity("2021-01-22","The coming-of-age journey of five fairies attending Alfea, a magical boarding school in the Otherworld where they must learn to master their powers while navigating love, rivalries, and the monsters that threaten their very existence.","en", listOf(10765, 18),"/oHj6guMrLfQcBzo3uxwBJc8Y736.jpg",listOf("US"),"/pwyMoXQbqJdmpjjl23KaaQLOv6S.jpg","Fate: The Winx Saga",417.684,8.5,"Fate: The Winx Saga",97175,486,false))
            tvshow.add(TVShowEntity("2011-04-17","Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakensin the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.","en", listOf(10765, 18, 10759),"/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",listOf("US"),"/suopoADq0k8YZr4dQXcU6pToj6s.jpg","Game of Thrones",420.479,8.4,"Game of Thrones",1399,12949,false))
            tvshow.add(TVShowEntity("2005-03-27","Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.","en", listOf(18),"/clnyhPqj1SNgpAdeSS6a6fwE6Bo.jpg",listOf("US"),"/edmk8xjGBsYVIf4QtLY9WMaMcXZ.jpg","Grey's Anatomy",699.432,8.2,"Grey's Anatomy",1416,5282,false))
            tvshow.add(TVShowEntity("2018-10-25","In a place where young witches, vampires, and werewolves are nurtured to be their best selves in spite of their worst impulses, Klaus Mikaelson’s daughter, 17-year-old Hope Mikaelson, Alaric Saltzman’s twins, Lizzie and Josie Saltzman, among others, come of age into heroes and villains at The Salvatore School for the Young and Gifted.","en", listOf(10765, 18),"/qTZIgXrBKURBK1KrsT7fe3qwtl9.jpg",listOf("US"),"/fRYwdeNjMqC30EhofPx5PlDpdun.jpg","Legacies",789.815,8.6,"Legacies",79460,1568,false))
            tvshow.add(TVShowEntity("2016-01-25","Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.","en", listOf(80, 10765),"/4EYPN5mVIhKLfxGruy7Dy41dTVn.jpg",listOf("US"),"/ta5oblpMlEcIPIS2YGcq9XEkWK2.jpg","Lucifer",568.786,8.5,"Lucifer",63174,7460,false))
            tvshow.add(TVShowEntity("2021-01-08","Inspired by the adventures of Arsène Lupin, gentleman thief Assane Diop sets out to avenge his father for an injustice inflicted by a wealthy family.","fr", listOf(80, 18, 9648),"/sgxawbFB5Vi5OkPWQLNfl3dvkNJ.jpg",listOf("FR"),"/dVHeJXUzHJJGadB2wvpuAn6fsdN.jpg","Lupin",334.653,7.9,"Lupin",96677,558,false))
            tvshow.add(TVShowEntity("2021-01-20","After realizing their babies were exchanged at birth, two women develop a plan to adjust to their new lives: creating a single —and peculiar— family.","es", listOf(35, 18),"/6chvnAakKI2cYW69ODBHZHm8clb.jpg",listOf("MX"),"/eAZtz2ydxBaHtJw3J42Gdy2DSpc.jpg","Madre solo hay dos",618.149,7.6,"Daughter From Another Mother",115857,540,false))
            tvshow.add(TVShowEntity("1995-04-24","Malhação is a Brazilian television series for the teenage audience. The soap started in 1995, and was set in a fictional Gym Club called Malhação on Barra da Tijuca, Rio de Janeiro. Through the years the location varied slightly. Although the name of the soap remains the same, it is now set in the Múltipla Escolha High School.","pt", listOf(10766),"/yn1nTW1aXTfztt6zFOGFPuObIaM.jpg",listOf("US"),"/yvIe2L1uGj0HOIbRKv6Sbdm2Mh7.jpg","Malhação",330.174,4.5,"Young Hearts",14424,10,false))
            tvshow.add(TVShowEntity("2021-01-08","Revisit the epic heroes, villains and moments from across the MCU in preparation for the stories still to come. Each dynamic segment feeds directly into thupcoming series — setting the stage for future events. This series weaves together the many threads that constitute the unparalleled Marvel Cinematic Universe.","en", listOf(99),"/EpDuYIK81YtCUT3gH2JDpyj8Qk.jpg",listOf("US"),"/wAEWZm2pSopAbqE5dQWE0ET8aR5.jpg","Marvel Studios: Legends",706.992,7.6,"Marvel Studios: Legends",114695,260,false))
            tvshow.add(TVShowEntity("2004-10-04","The series is set at the Elite Way School, a prestigious private boarding high school in Mexico City with a major plot line revolving around a group of students forming a pop band. Additional subplots involve the school's faculty and the students' parents. One trademark of the show is the random use of English words and phrases, often used by fresa characters.","es", listOf(35, 10766, 18),"/oO2wf3mdXWWWxr1hZdYxin0OCz4.jpg",listOf("US"),"/1D3 sDadfGOsYEjZT8N2V2MeGcTN.jpg","Rebelde",395.52,8.5,"Rebelde",12637,3633,false))
            tvshow.add(TVShowEntity("2017-01-26","Set in the present, the series offers a bold, subversive take on Archie, Betty, Veronica and their friends, exploring the surreality of small-town life, the darkness and weirdness bubbling beneath Riverdale’s wholesome facade.","en", listOf(9648, 18, 80),"/wRbjVBdDo5qHAEOVYoMWpM58FSA.jpg",listOf("US"),"/9hvhGtcsGhQY58pukw8w55UEUbL.jpg","Riverdale",1486.684,8.6,"Riverdale",69050,9762,false))
            tvshow.add(TVShowEntity("2020-05-17","Set more than seven years after the world has become a frozen wasteland, the remnants of humanity inhabit a gigantic, perpetually-moving train that circles the globe as class warfare, social injustice and the politics of survival play out.", "en", listOf(10765),"/95xQPSqwvQDRoB3rXUn4lRyJrBW.jpg",listOf("US"),"/2fhU42I8pPdvEKfrZtuJ8KrzdeF.jpg","Snowpiercer",406.247,7.5,"Snowpiercer",79680,497,false))
            tvshow.add(TVShowEntity("2017-09-25","A young surgeon with Savant syndrome is recruited into the surgical unit of a prestigious hospital. The question will arise: can a person who doesn have the ability to relate to people actually save their lives","en", listOf(18),"/6tfT03sGp9k4c0J3dypjrI8TSAI.jpg",listOf("US"),"/mZjZgY6ObiKtVuKVDrnS9VnuNlE.jpg","The Good Doctor",789.814,8.6,"The Good Doctor",71712,6779,false))
            tvshow.add(TVShowEntity("2019-11-12","After the fall of the Galactic Empire, lawlessness has spread throughout the galaxy. A lone gunfighter makes his way through the outer reaches,earning his keep as a bounty hunter.","en", listOf(10765, 10759),"/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg",listOf("US"),"/p7fwOnlxYYlB4A8U2b0JfX21Rr1.jpg","The Mandalorian",587.652,8.5,"The Mandalorian",82856,5768,false))
            tvshow.add(TVShowEntity("1989-12-16","Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, media and American life in general.","en", listOf(10751, 16, 35),"/2IWouZK4gkgHhJa3oyYuSWfSqbG.jpg",listOf("US"),"/hpU2cHC9tk90hswCFEpf5AtbqoL.jpg","The Simpsons",388.365,7.8,"The Simpsons",456,6034,false))
            tvshow.add(TVShowEntity("2009-09-10","The story of two vampire brothers obsessed with the same girl, who bears a striking resemblance to the beautiful but ruthless vampire they knew and loved in 1864.","en", listOf(18, 10765),"/aBkVgChtyyJaHyZh1gfd8DbzQon.jpg",listOf("US"),"/k7T9xRyzP41wBVNyNeLmh8Ch7gD.jpg","The Vampire Diaries",417.534,8.3,"The Vampire Diaries",18165,5154,false))
            tvshow.add(TVShowEntity("2013-03-03","The adventures of Ragnar Lothbrok, the greatest hero of his age. The series tells the sagas of Ragnar's band of Viking brothers and his family, as he rises to become King of the Viking tribes. As well as being a fearless warrior, Ragnar embodies the Norse traditions of devotion to the gods. Legend has it that he was a direct descendant of Odin, the god of war and warriors.","en", listOf(10759, 18),"/bQLrHIRNEkE3PdIWQrZHynQZazu.jpg",listOf("US"),"/aq2yEMgRQBPfRkrO0Repo2qhUAT.jpg","Vikings",607.853,8.0,"Vikings",44217,4055,false))
            tvshow.add(TVShowEntity("2021-01-15","Wanda Maximoff and Vision—two super-powered beings living idealized suburban lives—begin to suspect that everything is not as it seems.","en", listOf(10765, 9648, 18),"/glKDfE6btIRcVB5zrjspRIs4r52.jpg",listOf("US"),"/lOr9NKxh4vMweufMOUDJjJhCRHW.jpg","WandaVision",3342.43,8.4,"WandaVision",85271,4745,false))

        return  tvshow
    }


    fun generateRemoteDummyTVShow ()  : ArrayList<ResultsTVShowResponse> {

        val tvshow = ArrayList <ResultsTVShowResponse>()
        tvshow.add(ResultsTVShowResponse("2017-04-30","An ex-con becomes the traveling partner of a conman who turns out to be one of the older gods trying to recruit troops to battle the upstart deities. Based on Neil Gaiman's fantasy novel.","en", listOf(18, 9648, 10765),"/3KCAZaKHmoMIN9dHutqaMtubQqD.jpg",listOf("US"),"/7dnjFPoa22Yl3RKctp8kgUxiUg9.jpg","American Gods",344.643,7.1,"American Gods",46639,925))
        tvshow.add(ResultsTVShowResponse("2018-05-02","This Karate Kid sequel series picks up 30 years after the events of the 1984 All Valley Karate Tournament and finds Johnny Lawrence on the hunt for redemption by reopening the infamous Cobra Kai karate dojo. This reignites his old rivalry with the successful Daniel LaRusso, who has been working to maintain the balance in his life without mentor Mr. Miyagi.","en", listOf(10759, 18),"/obLBdhLxheKg8Li1qO11r2SwmYO.jpg",listOf("US"),"/gL8myjGc2qrmqVosyGm5CWTir9A.jpg","Cobra Kai",636.126,8.1,"Cobra Kai",77169,2481))
        tvshow.add(ResultsTVShowResponse("2021-01-22","The coming-of-age journey of five fairies attending Alfea, a magical boarding school in the Otherworld where they must learn to master their powers while navigating love, rivalries, and the monsters that threaten their very existence.","en", listOf(10765, 18),"/oHj6guMrLfQcBzo3uxwBJc8Y736.jpg",listOf("US"),"/pwyMoXQbqJdmpjjl23KaaQLOv6S.jpg","Fate: The Winx Saga",417.684,8.5,"Fate: The Winx Saga",97175,486))
        tvshow.add(ResultsTVShowResponse("2011-04-17","Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakensin the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.","en", listOf(10765, 18, 10759),"/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",listOf("US"),"/suopoADq0k8YZr4dQXcU6pToj6s.jpg","Game of Thrones",420.479,8.4,"Game of Thrones",1399,12949))
        tvshow.add(ResultsTVShowResponse("2005-03-27","Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.","en", listOf(18),"/clnyhPqj1SNgpAdeSS6a6fwE6Bo.jpg",listOf("US"),"/edmk8xjGBsYVIf4QtLY9WMaMcXZ.jpg","Grey's Anatomy",699.432,8.2,"Grey's Anatomy",1416,5282))
        tvshow.add(ResultsTVShowResponse("2018-10-25","In a place where young witches, vampires, and werewolves are nurtured to be their best selves in spite of their worst impulses, Klaus Mikaelson’s daughter, 17-year-old Hope Mikaelson, Alaric Saltzman’s twins, Lizzie and Josie Saltzman, among others, come of age into heroes and villains at The Salvatore School for the Young and Gifted.","en", listOf(10765, 18),"/qTZIgXrBKURBK1KrsT7fe3qwtl9.jpg",listOf("US"),"/fRYwdeNjMqC30EhofPx5PlDpdun.jpg","Legacies",789.815,8.6,"Legacies",79460,1568))
        tvshow.add(ResultsTVShowResponse("2016-01-25","Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.","en", listOf(80, 10765),"/4EYPN5mVIhKLfxGruy7Dy41dTVn.jpg",listOf("US"),"/ta5oblpMlEcIPIS2YGcq9XEkWK2.jpg","Lucifer",568.786,8.5,"Lucifer",63174,7460))
        tvshow.add(ResultsTVShowResponse("2021-01-08","Inspired by the adventures of Arsène Lupin, gentleman thief Assane Diop sets out to avenge his father for an injustice inflicted by a wealthy family.","fr", listOf(80, 18, 9648),"/sgxawbFB5Vi5OkPWQLNfl3dvkNJ.jpg",listOf("FR"),"/dVHeJXUzHJJGadB2wvpuAn6fsdN.jpg","Lupin",334.653,7.9,"Lupin",96677,558))
        tvshow.add(ResultsTVShowResponse("2021-01-20","After realizing their babies were exchanged at birth, two women develop a plan to adjust to their new lives: creating a single —and peculiar— family.","es", listOf(35, 18),"/6chvnAakKI2cYW69ODBHZHm8clb.jpg",listOf("MX"),"/eAZtz2ydxBaHtJw3J42Gdy2DSpc.jpg","Madre solo hay dos",618.149,7.6,"Daughter From Another Mother",115857,540))
        tvshow.add(ResultsTVShowResponse("1995-04-24","Malhação is a Brazilian television series for the teenage audience. The soap started in 1995, and was set in a fictional Gym Club called Malhação on Barra da Tijuca, Rio de Janeiro. Through the years the location varied slightly. Although the name of the soap remains the same, it is now set in the Múltipla Escolha High School.","pt", listOf(10766),"/yn1nTW1aXTfztt6zFOGFPuObIaM.jpg",listOf("US"),"/yvIe2L1uGj0HOIbRKv6Sbdm2Mh7.jpg","Malhação",330.174,4.5,"Young Hearts",14424,10))
        tvshow.add(ResultsTVShowResponse("2021-01-08","Revisit the epic heroes, villains and moments from across the MCU in preparation for the stories still to come. Each dynamic segment feeds directly into thupcoming series — setting the stage for future events. This series weaves together the many threads that constitute the unparalleled Marvel Cinematic Universe.","en", listOf(99),"/EpDuYIK81YtCUT3gH2JDpyj8Qk.jpg",listOf("US"),"/wAEWZm2pSopAbqE5dQWE0ET8aR5.jpg","Marvel Studios: Legends",706.992,7.6,"Marvel Studios: Legends",114695,260))
        tvshow.add(ResultsTVShowResponse("2004-10-04","The series is set at the Elite Way School, a prestigious private boarding high school in Mexico City with a major plot line revolving around a group of students forming a pop band. Additional subplots involve the school's faculty and the students' parents. One trademark of the show is the random use of English words and phrases, often used by fresa characters.","es", listOf(35, 10766, 18),"/oO2wf3mdXWWWxr1hZdYxin0OCz4.jpg",listOf("US"),"/1D3 sDadfGOsYEjZT8N2V2MeGcTN.jpg","Rebelde",395.52,8.5,"Rebelde",12637,3633))
        tvshow.add(ResultsTVShowResponse("2017-01-26","Set in the present, the series offers a bold, subversive take on Archie, Betty, Veronica and their friends, exploring the surreality of small-town life, the darkness and weirdness bubbling beneath Riverdale’s wholesome facade.","en", listOf(9648, 18, 80),"/wRbjVBdDo5qHAEOVYoMWpM58FSA.jpg",listOf("US"),"/9hvhGtcsGhQY58pukw8w55UEUbL.jpg","Riverdale",1486.684,8.6,"Riverdale",69050,9762))
        tvshow.add(ResultsTVShowResponse("2020-05-17","Set more than seven years after the world has become a frozen wasteland, the remnants of humanity inhabit a gigantic, perpetually-moving train that circles the globe as class warfare, social injustice and the politics of survival play out.", "en", listOf(10765),"/95xQPSqwvQDRoB3rXUn4lRyJrBW.jpg",listOf("US"),"/2fhU42I8pPdvEKfrZtuJ8KrzdeF.jpg","Snowpiercer",406.247,7.5,"Snowpiercer",79680,497))
        tvshow.add(ResultsTVShowResponse("2017-09-25","A young surgeon with Savant syndrome is recruited into the surgical unit of a prestigious hospital. The question will arise: can a person who doesn have the ability to relate to people actually save their lives","en", listOf(18),"/6tfT03sGp9k4c0J3dypjrI8TSAI.jpg",listOf("US"),"/mZjZgY6ObiKtVuKVDrnS9VnuNlE.jpg","The Good Doctor",789.814,8.6,"The Good Doctor",71712,6779))
        tvshow.add(ResultsTVShowResponse("2019-11-12","After the fall of the Galactic Empire, lawlessness has spread throughout the galaxy. A lone gunfighter makes his way through the outer reaches,earning his keep as a bounty hunter.","en", listOf(10765, 10759),"/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg",listOf("US"),"/p7fwOnlxYYlB4A8U2b0JfX21Rr1.jpg","The Mandalorian",587.652,8.5,"The Mandalorian",82856,5768))
        tvshow.add(ResultsTVShowResponse("1989-12-16","Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, media and American life in general.","en", listOf(10751, 16, 35),"/2IWouZK4gkgHhJa3oyYuSWfSqbG.jpg",listOf("US"),"/hpU2cHC9tk90hswCFEpf5AtbqoL.jpg","The Simpsons",388.365,7.8,"The Simpsons",456,6034))
        tvshow.add(ResultsTVShowResponse("2009-09-10","The story of two vampire brothers obsessed with the same girl, who bears a striking resemblance to the beautiful but ruthless vampire they knew and loved in 1864.","en", listOf(18, 10765),"/aBkVgChtyyJaHyZh1gfd8DbzQon.jpg",listOf("US"),"/k7T9xRyzP41wBVNyNeLmh8Ch7gD.jpg","The Vampire Diaries",417.534,8.3,"The Vampire Diaries",18165,5154))
        tvshow.add(ResultsTVShowResponse("2013-03-03","The adventures of Ragnar Lothbrok, the greatest hero of his age. The series tells the sagas of Ragnar's band of Viking brothers and his family, as he rises to become King of the Viking tribes. As well as being a fearless warrior, Ragnar embodies the Norse traditions of devotion to the gods. Legend has it that he was a direct descendant of Odin, the god of war and warriors.","en", listOf(10759, 18),"/bQLrHIRNEkE3PdIWQrZHynQZazu.jpg",listOf("US"),"/aq2yEMgRQBPfRkrO0Repo2qhUAT.jpg","Vikings",607.853,8.0,"Vikings",44217,4055))
        tvshow.add(ResultsTVShowResponse("2021-01-15","Wanda Maximoff and Vision—two super-powered beings living idealized suburban lives—begin to suspect that everything is not as it seems.","en", listOf(10765, 9648, 18),"/glKDfE6btIRcVB5zrjspRIs4r52.jpg",listOf("US"),"/lOr9NKxh4vMweufMOUDJjJhCRHW.jpg","WandaVision",3342.43,8.4,"WandaVision",85271,4745))

        return  tvshow
    }



}
